<?php


namespace Eniture\GlobalTranzLTLFreightQuotes\Model\Source;


class GlobalTranzCarriers
{
    public static function getCarriersArray()
    {
        return [
            'UPGF' => 'UPS Freight',
            'FXNL' => 'FedEx Freight Economy',
            'FXFE' => 'FedEx Freight Priority',
            'EXLA' => 'Estes Express',
            'RDWY' => 'YRC',
            'SAIA' => 'SAIA',
            'NPME' => 'New Penn',
            'FWDA' => 'Forward Air',
            'WARD' => 'Ward Trucking',
            'RDFS' => 'Roadrunner - Asset-Light',
            'PYLE' => 'A. Duie Pyle',
            'CTII' => 'Central Transport',
            'CLNI' => 'Clear Lane - Asset Lite',
            'BRTC' => 'BC Freightways',
            'VALC' => 'Valley Cartage',
            'EXDF' => 'Expedited Freight Systems',
            'HMES' => 'Holland',
            'SUON' => 'Sutton Transport',
            'AACT' => 'AAA Cooper',
            'AVRT' => 'Averitt Express',
            'PITD' => 'Pitt Ohio',
            'STDF' => 'Standard Forwarding',
            'CNWY' => 'XPO Logistics',
            'DHRN' => 'Dohrn Transfer Company',
            'ODFL' => 'Old Dominion Freight Line',
            'DAFG' => 'Dayton Freight',
            'RLCA' => 'R&L Carriers',
            'DLDS' => 'Diamond Line Delivery Systems',
            'OAKH' => 'Oak Harbor Freight Lines',
            'RETL' => 'Reddaway',
            'DDPP' => 'Dedicated Delivery Professionals',
            'DTST' => 'DATS Trucking',
            'DPHE' => 'Dependable Highway Express',
            'CENF' => 'Central Freight Lines',
            'XGSI' => 'Xpress Global Systems',
            'DOLR' => 'Dot-Line Transportation - Asset-Light',
            'DYLT' => 'Daylight Transport - Asset-Light',
        ];
    }

    public static function getImagesArray()
    {
        return [
            'aact',
            'aatj',
            'abfs',
            'avrt',
            'bahf',
            'beav',
            'bglf',
            'bkhd',
            'btnb',
            'btvp',
            'bxpe',
            'cenf',
            'cllq',
            'clni',
            'cnwy',
            'ctbv',
            'ctii',
            'dafg',
            'dhrn',
            'dolr',
            'dubl',
            'dylt',
            'echo',
            'edxi',
            'eqxt',
            'exla',
            'fcsy',
            'fdxg',
            'flan',
            'frcd',
            'frci',
            'fwdn',
            'fxnl',
            'gelj',
            'hmes',
            'laxv',
            'lkvl',
            'midw',
            'ncta',
            'nebt',
            'nemf',
            'npme',
            'oakh',
            'odfl',
            'paaf',
            'pana',
            'pitd',
            'ptwt',
            'pyle',
            'rblt',
            'rdfs',
            'rdtc',
            'rdwy',
            'retl',
            'rjwi',
            'rlca',
            'saia',
            'sefl',
            'sfpa',
            'smtl',
            'stdf',
            'towe',
            'tqyl',
            'ulrd',
            'upgf',
            'upsn',
            'usrd',
            'uvln',
            'ward',
            'xgsi',
            'yrca',
        ];
    }
}