<script>
    require(['jquery', 'domReady!'], function ($) {
        let carrierDiv = '#gtLtlCarriers_second-head';
        gtLtCurrentPlanNote($, '<?php echo $block->getPlanNotice(); ?>', carrierDiv);
    });

    function checkImage(imageSrc) {
        let img = new Image();
        try {
            img.src = imageSrc;
            return imageSrc;
        } catch(err) {
            return false;
        }
    }
</script>

<div class="main_container">
    <h2><strong>Cerasis Carriers</strong></h2>
    <div class="carriers_p">
        <p class="p1">
            Identifies which carriers are included in the quote response, not what is displayed in the shopping cart.
            Identify what displays in the shopping cart in the Quote Settings. For example, you may include quote
            responses from all carriers, but elect to only show the cheapest three in the shopping cart.
        </p>
        <p class="p2">
            Not all carriers service all origin and destination points. If a carrier doesn't service the ship to
            address, it is automatically omitted from the quote response. Consider conferring with GlobalTranz account team
            if you'd like to narrow the number of carrier responses.
        </p>
    </div>
    <div class="current_status">
        <span>Automatically enable new carriers</span>
        <input type="checkbox" class="auto_enable"
               onchange="return autoEnableNewCarriers('<?php echo $this->autoEnableCarriers(); ?>');" <?php echo($this->autoEnable == 'yes' ? 'checked' : ''); ?> />
        (<?php echo(isset($this->requestTime) ? $this->requestTime : '-- -- --'); ?>)
    </div>
    <div class="refresh_carriers">
        <a id="refresh_carriers" class="refresh_carriers_btn"
           onclick="return refreshCerasisCarriers('<?php echo $this->getCerasisCarriers(); ?>'); ">Refresh Carriers</a>
    </div>

    <table class="carrier" id="append_carriers">
        <thead>
        <tr>
            <th>Sr#</th>
            <th>Carrier Name</th>
            <th>Logo</th>
            <th><input type="checkbox" name="cerasisAllCarriers" class="selectAllServices"
                       onchange="return selectAllCarriers();" <?php echo (isset($this->selectedCarriers->cerasisAllCarriers) && $this->selectedCarriers->cerasisAllCarriers == 'on') ? 'checked' : '' ?>>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (isset($this->carriersList->carriers) && !empty($this->carriersList->carriers)) {
            $selectedCarriers = (array)$this->selectedCarriers;
            foreach ($this->carriersList->carriers as $key => $carriers) {
                $scac = $carriers->CarrierSCAC;
                $imgUrl = strpos($scac, 'blank') ? $block->getImgUrl($scac) : $this->getViewFileUrl('Eniture_GlobalTranzLTLFreightQuotes::images/'.strtolower($scac).'.png');
                ?>
                <tr id="row_<?php echo $key + 1; ?>" data-id="<?php echo $key + 1; ?>">
                    <td><?php echo $key + 1; ?></td>
                    <td><?php echo $carriers->CarrierName; ?></td>
                    <td><img src="<?php echo $this->getViewFileUrl('Eniture_GlobalTranzLTLFreightQuotes::images/'.strtolower($carriers->CarrierSCAC).'.png'); ?>"
                             name="<?php echo $scac; ?>" class="carrier-image" alt="logo"></td>
                    <td><input type="checkbox" class="cerasisQuoteServices" name="<?php echo $carriers->CarrierSCAC; ?>"
                               value="<?php echo $carriers->CarrierSCAC; ?>"
                               id="<?php $carriers->CarrierSCAC; ?>" <?php echo(in_array($carriers->CarrierSCAC, $selectedCarriers) ? "checked" : ""); ?> >
                    </td>
                </tr>
                <?php
            }
        } else { ?>
            <tr style="text-align: center;">
                <td colspan="4">No carrier available right now. Please refresh.</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
