<script>
    require(['jquery','domReady!'], function ($) {
        let carrierdiv = '#gtQuoteSetting_fourth-head';
        gtLtCurrentPlanNote($, '<?php echo $block->ltlPlanNotice(); ?>', carrierdiv);
        gtLtPlanQuoteRestriction('<?= $block->escapeJs(__($block->planRestriction())); ?>');

        gtRatingMethodComment();
        $('#gtQuoteSetting_fourth_ratingMethod').on('change', function () {
            gtRatingMethodComment(); //Add label on change rating methods
        });

        $("#gtQuoteSetting_fourth_shipDays").attr('size', '5');
        let ratingMthd   = $('#gtQuoteSetting_fourth_ratingMethod');

        let interval = setInterval(manipulateFields, 1000);
        function manipulateFields() {
            let ratVal  = ratingMthd.val();
            ratingMethod(ratVal);
            clearInterval(interval);
        }

        // Bind function on change
        ratingMthd.on('change', function (){
            let ratVal  = this.value;
            ratingMethod(ratVal);
        });

        function ratingMethod(ratVal) {
            let fields = ['.if_rm_13', '.if_rm_23', '.if_rm_12'];
            fields.forEach(function(entry) {
                if (entry.indexOf(ratVal) !== -1){
                    $(entry).closest('tr').show();
                } else {
                    $(entry).closest('tr').hide();
                }
            });
        }

    });
</script>
<?php
if ($block->enable == 'yes') {
    $block->setTemplate('Eniture_ResidentialAddressDetection::/system/config/residentialaddressdetection.phtml');
    echo $block->getHtml();
} else {
    ?>
    <div class="rad">
        <p>
                <?=
                $block->escapeHtml(__('Click <a href="%1" target="_blank">here</a> to add the Auto detect residential addresses module.(<a href="%2" target="_blank">Learn more</a>)', "https://eniture.com/magento2-residential-address-detection/", "https://eniture.com/magento2-residential-address-detection/#documentation"), ['a', 'div'])
                ?>
        </p>
    </div>
    <?php
}
